In [1]:
import pandas as pd

# 1. Load dataset
df = pd.read_excel(r"C:\Users\HARSH\OneDrive\Desktop\Retail_Internship_Project\data\raw\Online Retail.xlsx")

# 2. Drop rows with missing CustomerID or Description
df.dropna(subset=["CustomerID", "Description"], inplace=True)

# 3. Remove rows with Quantity <= 0 or UnitPrice <= 0
df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]

# 4. Convert CustomerID to string, InvoiceDate to datetime
df["CustomerID"] = df["CustomerID"].astype(str)
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

# 5. Add TotalPrice column
df["TotalPrice"] = df["Quantity"] * df["UnitPrice"]

# 6. Save to cleaned CSV
output_path = r"C:\Users\HARSH\OneDrive\Desktop\Retail_Internship_Project\data\cleaned\retail_cleaned.csv"
df.to_csv(output_path, index=False)

print("✅ Cleaning complete. Data saved to:", output_path)
print("Shape:", df.shape)
df.head()

✅ Cleaning complete. Data saved to: C:\Users\HARSH\OneDrive\Desktop\Retail_Internship_Project\data\cleaned\retail_cleaned.csv
Shape: (397884, 9)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34