In [1]:
import pandas as pd

# Load cleaned data
df = pd.read_csv(r"C:\Users\HARSH\OneDrive\Desktop\Retail_Internship_Project\data\cleaned\retail_cleaned.csv", parse_dates=["InvoiceDate"])

# Reference date for recency (max date in dataset)
snapshot_date = df["InvoiceDate"].max()

# Group by customer
customer_df = df.groupby("CustomerID").agg({
    "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
    "InvoiceNo": "nunique",
    "TotalPrice": "sum",
    "Quantity": "sum",
    "Description": "nunique"
}).rename(columns={
    "InvoiceDate": "Recency",
    "InvoiceNo": "Frequency",
    "TotalPrice": "Monetary",
    "Quantity": "TotalItems",
    "Description": "DistinctItems"
})

# Average basket size and value
customer_df["AvgBasketSize"] = customer_df["TotalItems"] / customer_df["Frequency"]
customer_df["AvgBasketValue"] = customer_df["Monetary"] / customer_df["Frequency"]

# Drop TotalItems (intermediate)
customer_df.drop(columns=["TotalItems"], inplace=True)

# Reset index
customer_df.reset_index(inplace=True)

# Save engineered dataset
output_path = r"C:\Users\HARSH\OneDrive\Desktop\Retail_Internship_Project\data\cleaned\customer_features.csv"
customer_df.to_csv(output_path, index=False)

print("✅ Feature engineering complete. Saved to:", output_path)
customer_df.head()

✅ Feature engineering complete. Saved to: C:\Users\HARSH\OneDrive\Desktop\Retail_Internship_Project\data\cleaned\customer_features.csv

,CustomerID,Recency,Frequency,Monetary,DistinctItems,AvgBasketSize,AvgBasketValue
0,12346.0,325,1,77183.60,1,74215.000000,77183.600000
1,12347.0,1,7,4310.00,103,351.142857,615.714286
2,12348.0,74,4,1797.24,22,585.250000,449.310000
3,12349.0,18,1,1757.55,73,631.000000,1757.550000
4,12350.0,309,1,334.40,17,197.000000,334.400000